/*
 * Created on 2023-06-14 ( 19:31:39 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.yamaha.entities;

import java.io.Serializable;
import java.math.BigInteger;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity class for "UserMaster"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="user_master", schema="public" )
public class UserMaster implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="username", nullable=false, length=2147483647)
    private String     username ;

    //--- ENTITY DATA FIELDS 
    @Column(name="fullname", length=2147483647)
    private String     fullname ;
    
    @Column(name="phoneNo")
    private BigInteger    phoneno ;

    //--- ENTITY DATA FIELDS 
    @Column(name="email", length=2147483647)
    private String     email ;

    @Column(name="password", length=2147483647)
    private String     password ;

    @Column(name="usercode")
    private Integer    usercode ;

    
    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    
    public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getFullname() {
		return fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public BigInteger getPhoneno() {
		return phoneno;
	}

	public void setPhoneno(BigInteger phoneno) {
		this.phoneno = phoneno;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getUsercode() {
		return usercode;
	}

	public void setUsercode(Integer usercode) {
		this.usercode = usercode;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public String toString() {
		return "UserMaster [username=" + username + ", fullname=" + fullname + ", phoneno=" + phoneno + ", email="
				+ email + ", password=" + password + ", usercode=" + usercode + "]";
	}

	public UserMaster(String username, String fullname, BigInteger phoneno, String email, String password,
			Integer usercode) {
		super();
		this.username = username;
		this.fullname = fullname;
		this.phoneno = phoneno;
		this.email = email;
		this.password = password;
		this.usercode = usercode;
	}

	public UserMaster() {
		super();
		// TODO Auto-generated constructor stub
	}
    
	
	
	
}
